---

rules:
  body-leading-blank:
    - 1
    - always
  body-max-line-length:
    - 2
    - always
    - 100
  footer-leading-blank:
    - 1
    - always
  footer-max-line-length:
    - 2
    - always
    - 100
  header-max-length:
    - 2
    - always
    - 100
  subject-case:
  # Technically there is not "sentence case" standard in Conventional Commits
  # https://www.conventionalcommits.org/en/v1.0.0/
    - 2
    - always
    - - lower-case      # default
      - upper-case      # UPPERCASE
      - camel-case      # camelCase
      - kebab-case      # kebab-case
      - pascal-case     # PascalCase
      - sentence-case   # Sentence case
      - snake-case      # snake_case
      - start-case      # Start Case
  subject-empty:
    - 2
    - never
  subject-full-stop:
    - 2
    - never
    - "."
  type-case:
    - 2
    - always
    - lower-case
  type-empty:
    - 2
    - never
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - style
      - refactor
      - perf
      - test
      - build
      - ci
      - chore
      - revert
help: |
  **Possible types**:
  feat:     Adds a new feature.
  fix:      Solves a bug.
  docs:     Adds or alters documentation.
  style:
  refactor: Rewrites code without feature, performance or bug changes.
  perf:     Improves performance.
  test:     Adds or modifies tests.
  build:
  ci:       Changes to our CI configuration files and scripts
  chore:    Change build process, tooling or dependencies.
  revert:   Changes that reverting other changes

...
